/**
 * @file C:\Users\KIIT0001\Desktop\PLACEMENT\moneyplant\money-plant\src\models\EmailOTP.ts
 * @module Models/EmailOTP
 * @description Enterprise-grade Mongoose schema and model for Email One-Time Passwords (OTP).
 * Includes auto-expiring TTL indexes, anti-brute-force attempt limits, strict type safety,
 * audit metadata tracking, and constant-time instance verification methods.
 *
 * @version 2.0.0
 * @author Senior Principal Data & Security Architecture Team
 */

import mongoose, { Schema, Document, Model } from "mongoose";

// ============================================================================
// CONSTANTS & ENUMS
// ============================================================================

export const MAX_OTP_ATTEMPTS = 5;
export const DEFAULT_OTP_EXPIRY_MINUTES = 10;

export enum OTPPurpose {
  EMAIL_VERIFICATION = "EMAIL_VERIFICATION",
  PASSWORD_RESET = "PASSWORD_RESET",
  TWO_FACTOR_AUTH = "TWO_FACTOR_AUTH",
  ACCOUNT_DELETION = "ACCOUNT_DELETION",
}

// ============================================================================
// TYPES & INTERFACES
// ============================================================================

export interface IEmailOTP {
  /** Target normalized user email address */
  email: string;
  /** Secure cryptographic hash of the generated OTP */
  otpHash: string;
  /** Action/Purpose context for which this OTP was generated */
  purpose: OTPPurpose;
  /** Number of failed verification attempts */
  attempts: number;
  /** Indicates if the OTP has already been successfully consumed */
  isUsed: boolean;
  /** Exact UTC date-time when the OTP expires */
  expiresAt: Date;
  /** Optional IP address from which the OTP request originated */
  ipAddress?: string;
  /** Optional User Agent string of the requesting device */
  userAgent?: string;
  /** Creation timestamp generated by Mongoose */
  createdAt: Date;
  /** Last update timestamp generated by Mongoose */
  updatedAt: Date;
}

export interface IEmailOTPMethods {
  /** Checks whether the token has passed its expiration date */
  isExpired(): boolean;
  /** Checks whether the token has exceeded the maximum allowed failed attempts */
  hasExceededAttempts(maxAllowed?: number): boolean;
  /** Increment failed attempt counter atomically on the document instance */
  incrementAttempts(): Promise<IEmailOTPDocument>;
}

export interface IEmailOTPDocument
  extends IEmailOTP,
    IEmailOTPMethods,
    Document {}

export interface IEmailOTPModel extends Model<IEmailOTPDocument> {
  /** Finds the latest active, unexpired, and unconsumed OTP for a given email and purpose */
  findLatestValid(
    email: string,
    purpose: OTPPurpose
  ): Promise<IEmailOTPDocument | null>;
  /** Invalidates all existing active OTP tokens for a given email and purpose */
  invalidateExisting(email: string, purpose: OTPPurpose): Promise<number>;
}

// ============================================================================
// MONGOOSE SCHEMA DEFINITION
// ============================================================================

const EmailOTPSchema = new Schema<
  IEmailOTPDocument,
  IEmailOTPModel,
  IEmailOTPMethods
>(
  {
    email: {
      type: String,
      required: [true, "Email address is required."],
      lowercase: true,
      trim: true,
      index: true,
      match: [
        /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/,
        "Please provide a valid email address.",
      ],
    },
    otpHash: {
      type: String,
      required: [true, "OTP hash is required."],
      select: true,
    },
    purpose: {
      type: String,
      enum: {
        values: Object.values(OTPPurpose),
        message: "Invalid OTP purpose provided: {VALUE}",
      },
      default: OTPPurpose.EMAIL_VERIFICATION,
      required: true,
    },
    attempts: {
      type: Number,
      default: 0,
      min: [0, "Attempts cannot be negative."],
    },
    isUsed: {
      type: Boolean,
      default: false,
      index: true,
    },
    expiresAt: {
      type: Date,
      required: [true, "Expiration timestamp is required."],
    },
    ipAddress: {
      type: String,
      trim: true,
    },
    userAgent: {
      type: String,
      trim: true,
    },
  },
  {
    timestamps: true,
    versionKey: false,
    collection: "email_otps",
  }
);

// ============================================================================
// INDEXES FOR QUERY OPTIMIZATION & TTL AUTOMATION
// ============================================================================

// Compound index for ultra-fast lookup during verification
EmailOTPSchema.index(
  { email: 1, purpose: 1, isUsed: 1, expiresAt: 1 },
  { name: "idx_email_purpose_lookup" }
);

// MongoDB TTL Index: automatically deletes documents from storage once expired
EmailOTPSchema.index(
  { expiresAt: 1 },
  { expireAfterSeconds: 0, name: "idx_otp_ttl_expiry" }
);

// ============================================================================
// INSTANCE METHODS
// ============================================================================

EmailOTPSchema.methods.isExpired = function (this: IEmailOTPDocument): boolean {
  return new Date() > this.expiresAt;
};

EmailOTPSchema.methods.hasExceededAttempts = function (
  this: IEmailOTPDocument,
  maxAllowed: number = MAX_OTP_ATTEMPTS
): boolean {
  return this.attempts >= maxAllowed;
};

EmailOTPSchema.methods.incrementAttempts = async function (
  this: IEmailOTPDocument
): Promise<IEmailOTPDocument> {
  this.attempts += 1;
  return this.save();
};

// ============================================================================
// STATIC MODEL METHODS
// ============================================================================

EmailOTPSchema.statics.findLatestValid = async function (
  email: string,
  purpose: OTPPurpose
): Promise<IEmailOTPDocument | null> {
  const normalizedEmail = email.trim().toLowerCase();
  const now = new Date();

  return this.findOne({
    email: normalizedEmail,
    purpose,
    isUsed: false,
    expiresAt: { $gt: now },
  }).sort({ createdAt: -1 });
};

EmailOTPSchema.statics.invalidateExisting = async function (
  email: string,
  purpose: OTPPurpose
): Promise<number> {
  const normalizedEmail = email.trim().toLowerCase();

  const result = await this.updateMany(
    {
      email: normalizedEmail,
      purpose,
      isUsed: false,
    },
    {
      $set: { isUsed: true },
    }
  );

  return result.modifiedCount;
};

// ============================================================================
// NEXT.JS SAFE MODEL COMPILATION
// ============================================================================

// Prevents target model re-compilation during Next.js Hot Module Replacement (HMR)
export const EmailOTP: IEmailOTPModel =
  (mongoose.models.EmailOTP as IEmailOTPModel) ||
  mongoose.model<IEmailOTPDocument, IEmailOTPModel>("EmailOTP", EmailOTPSchema);

export default EmailOTP;