/**
 * @file C:\Users\KIIT0001\Desktop\PLACEMENT\moneyplant\money-plant\src\models\PasswordResetOTP.ts
 * @module Models/PasswordResetOTP
 * @description Enterprise-grade Mongoose schema and model for Password Reset One-Time Passwords (OTP).
 * Features auto-expiring TTL indexes, anti-brute-force attempt limits, strict type safety,
 * audit metadata tracking, and static lifecycle management methods.
 *
 * @version 2.0.0
 * @author Senior Principal Data & Security Architecture Team
 */

import mongoose, { Schema, Document, Model } from "mongoose";

// ============================================================================
// CONSTANTS & CONFIGURATION
// ============================================================================

export const MAX_PASSWORD_RESET_ATTEMPTS = 5;
export const DEFAULT_PASSWORD_RESET_EXPIRY_MINUTES = 15;

// ============================================================================
// TYPES & INTERFACES
// ============================================================================

export interface IPasswordResetOTP {
  /** Target normalized user email address */
  email: string;
  /** Secure cryptographic hash of the generated OTP */
  otpHash: string;
  /** Number of failed verification attempts */
  attempts: number;
  /** Indicates if the OTP has already been consumed for a password reset */
  isUsed: boolean;
  /** Timestamp when the password reset process was completed */
  resetCompletedAt?: Date;
  /** Exact UTC date-time when the OTP expires */
  expiresAt: Date;
  /** Optional IP address from which the password reset request originated */
  ipAddress?: string;
  /** Optional User Agent string of the requesting device */
  userAgent?: string;
  /** Creation timestamp generated by Mongoose */
  createdAt: Date;
  /** Last update timestamp generated by Mongoose */
  updatedAt: Date;
}

export interface IPasswordResetOTPMethods {
  /** Checks whether the reset token has passed its expiration date */
  isExpired(): boolean;
  /** Checks whether the reset token has exceeded the maximum allowed failed attempts */
  hasExceededAttempts(maxAllowed?: number): boolean;
  /** Increments the failed attempt counter atomically on the document instance */
  incrementAttempts(): Promise<IPasswordResetOTPDocument>;
  /** Marks the token as consumed and records completion timestamp */
  markAsUsed(): Promise<IPasswordResetOTPDocument>;
}

export interface IPasswordResetOTPDocument
  extends IPasswordResetOTP,
    IPasswordResetOTPMethods,
    Document {}

export interface IPasswordResetOTPModel extends Model<IPasswordResetOTPDocument> {
  /** Finds the latest active, unexpired, and unconsumed password reset OTP for an email */
  findLatestActive(email: string): Promise<IPasswordResetOTPDocument | null>;
  /** Invalidates all active password reset OTP tokens for an email */
  invalidateAllForEmail(email: string): Promise<number>;
}

// ============================================================================
// MONGOOSE SCHEMA DEFINITION
// ============================================================================

const PasswordResetOTPSchema = new Schema<
  IPasswordResetOTPDocument,
  IPasswordResetOTPModel,
  IPasswordResetOTPMethods
>(
  {
    email: {
      type: String,
      required: [true, "Email address is required for password reset."],
      lowercase: true,
      trim: true,
      index: true,
      match: [
        /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/,
        "Please provide a valid email address.",
      ],
    },
    otpHash: {
      type: String,
      required: [true, "OTP hash is required."],
      select: true,
    },
    attempts: {
      type: Number,
      default: 0,
      min: [0, "Attempts cannot be negative."],
    },
    isUsed: {
      type: Boolean,
      default: false,
      index: true,
    },
    resetCompletedAt: {
      type: Date,
      default: null,
    },
    expiresAt: {
      type: Date,
      required: [true, "Expiration timestamp is required."],
    },
    ipAddress: {
      type: String,
      trim: true,
    },
    userAgent: {
      type: String,
      trim: true,
    },
  },
  {
    timestamps: true,
    versionKey: false,
    collection: "password_reset_otps",
  }
);

// ============================================================================
// INDEXES FOR QUERY OPTIMIZATION & TTL AUTOMATION
// ============================================================================

// Compound index for ultra-fast lookup during password reset verification
PasswordResetOTPSchema.index(
  { email: 1, isUsed: 1, expiresAt: 1 },
  { name: "idx_password_reset_lookup" }
);

// MongoDB TTL Index: automatically deletes documents from storage once expired
PasswordResetOTPSchema.index(
  { expiresAt: 1 },
  { expireAfterSeconds: 0, name: "idx_password_reset_ttl_expiry" }
);

// ============================================================================
// INSTANCE METHODS
// ============================================================================

PasswordResetOTPSchema.methods.isExpired = function (
  this: IPasswordResetOTPDocument
): boolean {
  return new Date() > this.expiresAt;
};

PasswordResetOTPSchema.methods.hasExceededAttempts = function (
  this: IPasswordResetOTPDocument,
  maxAllowed: number = MAX_PASSWORD_RESET_ATTEMPTS
): boolean {
  return this.attempts >= maxAllowed;
};

PasswordResetOTPSchema.methods.incrementAttempts = async function (
  this: IPasswordResetOTPDocument
): Promise<IPasswordResetOTPDocument> {
  this.attempts += 1;
  return this.save();
};

PasswordResetOTPSchema.methods.markAsUsed = async function (
  this: IPasswordResetOTPDocument
): Promise<IPasswordResetOTPDocument> {
  this.isUsed = true;
  this.resetCompletedAt = new Date();
  return this.save();
};

// ============================================================================
// STATIC MODEL METHODS
// ============================================================================

PasswordResetOTPSchema.statics.findLatestActive = async function (
  email: string
): Promise<IPasswordResetOTPDocument | null> {
  const normalizedEmail = email.trim().toLowerCase();
  const now = new Date();

  return this.findOne({
    email: normalizedEmail,
    isUsed: false,
    expiresAt: { $gt: now },
  }).sort({ createdAt: -1 });
};

PasswordResetOTPSchema.statics.invalidateAllForEmail = async function (
  email: string
): Promise<number> {
  const normalizedEmail = email.trim().toLowerCase();

  const result = await this.updateMany(
    {
      email: normalizedEmail,
      isUsed: false,
    },
    {
      $set: { isUsed: true },
    }
  );

  return result.modifiedCount;
};

// ============================================================================
// NEXT.JS SAFE MODEL COMPILATION
// ============================================================================

// Prevents target model re-compilation during Next.js Hot Module Replacement (HMR)
export const PasswordResetOTP: IPasswordResetOTPModel =
  (mongoose.models.PasswordResetOTP as IPasswordResetOTPModel) ||
  mongoose.model<IPasswordResetOTPDocument, IPasswordResetOTPModel>(
    "PasswordResetOTP",
    PasswordResetOTPSchema
  );

export default PasswordResetOTP;